const alimentos = [
  {
    id: 1,
    nombre: "Manzana",
    grupo: 3,
    imagen: "imagenes/manzana.webp",
    mostrado: false,
  },
  {
    id: 2,
    nombre: "Plátano",
    grupo: 3,
    imagen: "imagenes/platano.webp",
    mostrado: false,
  },

  {
    id: 3,
    nombre: "Zanahoria",
    grupo: 3,
    imagen: "imagenes/zanahoria.webp",
    mostrado: false,
  },
  {
    id: 4,
    nombre: "Brócoli",
    grupo: 3,
    imagen: "imagenes/brocoli.webp",
    mostrado: false,
  },

  {
    id: 5,
    nombre: "Leche",
    grupo: 4,
    imagen: "imagenes/leche.webp",
    mostrado: false,
  },
  {
    id: 6,
    nombre: "Queso",
    grupo: 4,
    imagen: "imagenes/queso.webp",
    mostrado: false,
  },

  {
    id: 7,
    nombre: "Pollo",
    grupo: 4,
    imagen: "imagenes/pollo.webp",
    mostrado: false,
  },
  {
    id: 8,
    nombre: "Huevo",
    grupo: 4,
    imagen: "imagenes/huevo.webp",
    mostrado: false,
  },

  {
    id: 9,
    nombre: "Pan",
    grupo: 2,
    imagen: "imagenes/pan.webp",
    mostrado: false,
  },
  {
    id: 10,
    nombre: "Arroz",
    grupo: 2,
    imagen: "imagenes/arroz.webp",
    mostrado: false,
  },

  {
    id: 11,
    nombre: "Aceite",
    grupo: 3,
    imagen: "imagenes/aceite.webp",
    mostrado: false,
  },
  {
    id: 12,
    nombre: "Mantequilla",
    grupo: 6,
    imagen: "imagenes/mantequilla.webp",
    mostrado: false,
  },
  {
    id: 13,
    nombre: "Abichuelas",
    grupo: 4,
    imagen: "imagenes/abichuelas.webp",
    mostrado: false,
  },
  {
    id: 14,
    nombre: "Agua",
    grupo: 1,
    imagen: "imagenes/agua.webp",
    mostrado: false,
  },
  {
    id: 15,
    nombre: "Alcachofa",
    grupo: 3,
    imagen: "imagenes/alcachofa.webp",
    mostrado: false,
  },
  {
    id: 17,
    nombre: "Almendra",
    grupo: 4,
    imagen: "imagenes/almendra.webp",
    mostrado: false,
  },
  {
    id: 18,
    nombre: "Carne Roja",
    grupo: 5,
    imagen: "imagenes/carne.webp",
    mostrado: false,
  },
  {
    id: 19,
    nombre: "Cebolla",
    grupo: 3,
    imagen: "imagenes/cebolla.webp",
    mostrado: false,
  },
  {
    id: 20,
    nombre: "Guinda",
    grupo: 3,
    imagen: "imagenes/guinda.webp",
    mostrado: false,
  },
  {
    id: 21,
    nombre: "Chorizo",
    grupo: 5,
    imagen: "imagenes/chorizo.webp",
    mostrado: false,
  },
  {
    id: 22,
    nombre: "Conejo",
    grupo: 4,
    imagen: "imagenes/conejo.webp",
    mostrado: false,
  },
  {
    id: 23,
    nombre: "Croissant",
    grupo: 6,
    imagen: "imagenes/croisan.webp",
    mostrado: false,
  },
  {
    id: 24,
    nombre: "Garbanzos",
    grupo: 4,
    imagen: "imagenes/garbanzo.webp",
    mostrado: false,
  },
  {
    id: 25,
    nombre: "Harina",
    grupo: 2,
    imagen: "imagenes/harina.webp",
    mostrado: false,
  },
  {
    id: 26,
    nombre: "Helado",
    grupo: 6,
    imagen: "imagenes/helado.webp",
    mostrado: false,
  },
  {
    id: 27,
    nombre: "Lechuga",
    grupo: 3,
    imagen: "imagenes/lechuga.webp",
    mostrado: false,
  },
  {
    id: 28,
    nombre: "Lentejas",
    grupo: 4,
    imagen: "imagenes/lentejas.webp",
    mostrado: false,
  },
  {
    id: 29,
    nombre: "Longaniza",
    grupo: 5,
    imagen: "imagenes/longaniza.webp",
    mostrado: false,
  },
  {
    id: 30,
    nombre: "Macarrones",
    grupo: 2,
    imagen: "imagenes/macarrones.webp",
    mostrado: false,
  },
  {
    id: 31,
    nombre: "Magdalena",
    grupo: 6,
    imagen: "imagenes/magdalena.webp",
    mostrado: false,
  },
  {
    id: 32,
    nombre: "Morcilla",
    grupo: 5,
    imagen: "imagenes/morcilla.webp",
    mostrado: false,
  },
  {
    id: 33,
    nombre: "Mortadela",
    grupo: 5,
    imagen: "imagenes/mortadela.webp",
    mostrado: false,
  },
  {
    id: 34,
    nombre: "Naranja",
    grupo: 3,
    imagen: "imagenes/naranja.webp",
    mostrado: false,
  },
  {
    id: 35,
    nombre: "Nuez",
    grupo: 4,
    imagen: "imagenes/nuez.webp",
    mostrado: false,
  },
  {
    id: 36,
    nombre: "Patatas",
    grupo: 2,
    imagen: "imagenes/patata.webp",
    mostrado: false,
  },
  {
    id: 37,
    nombre: "Pera",
    grupo: 3,
    imagen: "imagenes/pera.webp",
    mostrado: false,
  },
  {
    id: 38,
    nombre: "Pescado",
    grupo: 4,
    imagen: "imagenes/pescado.webp",
    mostrado: false,
  },
  {
    id: 39,
    nombre: "Pimiento",
    grupo: 3,
    imagen: "imagenes/pimiento.webp",
    mostrado: false,
  },
  {
    id: 40,
    nombre: "Salchicha",
    grupo: 5,
    imagen: "imagenes/salchicha.webp",
    mostrado: false,
  },
  {
    id: 41,
    nombre: "Sandía",
    grupo: 3,
    imagen: "imagenes/sandia.webp",
    mostrado: false,
  },
  {
    id: 42,
    nombre: "Espagueti",
    grupo: 2,
    imagen: "imagenes/espagueti.webp",
    mostrado: false,
  },
  {
    id: 43,
    nombre: "Tomate",
    grupo: 3,
    imagen: "imagenes/tomate.webp",
    mostrado: false,
  },
  {
    id: 44,
    nombre: "Uvas",
    grupo: 3,
    imagen: "imagenes/uva.webp",
    mostrado: false,
  },
  {
    id: 45,
    nombre: "Yogurt",
    grupo: 4,
    imagen: "imagenes/yogur.webp",
    mostrado: false,
  },
  {
    id: 46,
    nombre: "Anillas",
    grupo: 1,
    imagen: "imagenes/anillas.webp",
    mostrado: false,
  },
  {
    id: 47,
    nombre: "Bádminton",
    grupo: 1,
    imagen: "imagenes/badminton.webp",
    mostrado: false,
  },
  {
    id: 48,
    nombre: "Baloncesto",
    grupo: 1,
    imagen: "imagenes/baloncesto.webp",
    mostrado: false,
  },
  {
    id: 49,
    nombre: "Castañas",
    grupo: 2,
    imagen: "imagenes/castana.webp",
    mostrado: false,
  },
  {
    id: 50,
    nombre: "Ciclismo",
    grupo: 1,
    imagen: "imagenes/ciclismo.webp",
    mostrado: false,
  },
  {
    id: 51,
    nombre: "Cocinar sano",
    grupo: 1,
    imagen: "imagenes/cocinaSano.webp",
    mostrado: false,
  },
  {
    id: 52,
    nombre: "Correr",
    grupo: 1,
    imagen: "imagenes/correr.webp",
    mostrado: false,
  },
  {
    id: 53,
    nombre: "Dormir suficiente",
    grupo: 1,
    imagen: "imagenes/dormir.webp",
    mostrado: false,
  },
  {
    id: 54,
    nombre: "Equilibrio emocional",
    grupo: 1,
    imagen: "imagenes/equilibrio.webp",
    mostrado: false,
  },
  {
    id: 55,
    nombre: "Escalada",
    grupo: 1,
    imagen: "imagenes/escalada.webp",
    mostrado: false,
  },
  {
    id: 56,
    nombre: "Fúbol",
    grupo: 1,
    imagen: "imagenes/futbol.webp",
    mostrado: false,
  },
  {
    id: 57,
    nombre: "Guisantes",
    grupo: 2,
    imagen: "imagenes/guisantes.webp",
    mostrado: false,
  },
  {
    id: 58,
    nombre: "Habas",
    grupo: 2,
    imagen: "imagenes/habas.webp",
    mostrado: false,
  },
  {
    id: 59,
    nombre: "Judías",
    grupo: 2,
    imagen: "imagenes/judias.webp",
    mostrado: false,
  },
  {
    id: 60,
    nombre: "Natación",
    grupo: 1,
    imagen: "imagenes/natacion.webp",
    mostrado: false,
  },
  {
    id: 61,
    nombre: "Pasta",
    grupo: 2,
    imagen: "imagenes/pasta.webp",
    mostrado: false,
  },
  {
    id: 62,
    nombre: "Control de peso",
    grupo: 1,
    imagen: "imagenes/peso.webp",
    mostrado: false,
  },
  {
    id: 63,
    nombre: "Tenis",
    grupo: 1,
    imagen: "imagenes/tenis.webp",
    mostrado: false,
  },
];
